spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  r2dbc:
    url: r2dbc:mysql://user:password@localhost:3306/mdd_db
