version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: mdd-postgres
    restart: always
    environment:
      POSTGRES_DB: mdd_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
