services:
  # Base de données PostgreSQL (port hôte élevé pour éviter conflits)
  postgres:
    image: postgres:16
    container_name: mdd-postgres
    restart: always
    environment:
      POSTGRES_DB: mdd_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
# Volumes pour persistance des données
volumes:
  postgres_data: