github:
  token: ${GITHUB_TOKEN:}
server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "https://legendary-space-bassoon-597p4vxjgq52pxgg-4200.app.github.dev"
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/user/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**, /api/themes/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

  r2dbc:
    url: r2dbc:postgresql://mdd-postgres:5432/mdd_db
    username: user
    password: password

eureka:
  instance:
    hostname: api-gateway
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

jwt:
  secret: your-very-long-and-secure-secret-key-that-is-at-least-256-bits
  expiration: 86400 # 24 hours in seconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
