server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
