spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://user:password@localhost:3306/mdd_db

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
