# Configuration pour l'environnement Docker
spring:
  profiles:
    active: docker
  
  # Configuration base de données
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:mdd}
    username: ${POSTGRES_USER:mdd_user}
    password: ${POSTGRES_PASSWORD:mdd_password}
    driver-class-name: org.postgresql.Driver
  
  # Configuration JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

# Configuration serveur
server:
  port: 8080
  servlet:
    context-path: /api

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:monSecretJwtTresSolideEtComplexeQuiDoitFaireAuMoins32Caracteres}
  expiration: 86400000 # 24 heures en millisecondes

# Configuration logging
logging:
  level:
    com.elducche.mdd: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
