spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://mdd-postgres:5432/mdd_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: mdd-post-service
    prefer-ip-address: true
    non-secure-port: 8082
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: your-super-secret-key-that-is-long-enough-to-be-secure
