spring:
  application:
    name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mdd-postgres:5432/mdd_db
    username: user
    password: password
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:/schema.sql

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: post-service

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

jwt:
  expiration: 86400 # 24 hours