spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://mdd-postgres:5432/mdd_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka
  instance:
    hostname: improved-tribble-jgpw4rqv56g25pr4-8082.app.github.dev
    prefer-ip-address: false
    non-secure-port: 8082
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: your-super-secret-key-that-is-long-enough-to-be-secure
