spring:
  applieureka:
  client:
    serviceUrl:
      defaultZone: http://mdd-discovery-server:8761/eureka
  instance:
    hostname: mdd-post-service
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:defaultSecretKey}:
    name: post-service
  datasource:
    url: jdbc:postgresql://mdd-postgres:5432/mdd_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://mdd-discovery-server:8761/eureka
  instance:
    hostname: mdd-post-service
    prefer-ip-address: true

jwt:
  secret: mySecretKey
  expiration: 86400
